"""articles

Os artigos do site, escritos pela loja no painel.

Revision ID: 8c917f7e4d09
Revises: 9fc7a307c5f1
Create Date: 2026-08-18 16:17:37.029521
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8c917f7e4d09'
down_revision: str | None = '9fc7a307c5f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('cover_path', sa.String(length=500), nullable=True),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('reading_minutes', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='article_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_status_published', 'articles', ['status', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_slug'), 'articles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_slug'), table_name='articles')
    op.drop_index('ix_article_status_published', table_name='articles')
    op.drop_table('articles')

    # O autogenerate NÃO gera esta linha: no Postgres o ENUM é objeto
    # independente da tabela e sobrevive ao DROP TABLE. Sem removê-lo, um
    # upgrade posterior falha com "type article_status already exists" — e o erro
    # aparece só no segundo ciclo, longe da causa.
    op.execute(sa.text("DROP TYPE IF EXISTS article_status"))
