"""schema inicial

Revision ID: f67f2e62f862
Revises:
Create Date: 2026-07-14 15:15:54.889541
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f67f2e62f862"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # -------------------------------------------------------------------------
    # Configuração de busca textual em português, insensível a acento.
    #
    # Vem ANTES das tabelas porque a coluna gerada `vehicles.search_vector`
    # referencia esta configuração, e o Postgres exige que ela já exista.
    #
    # Por que não a config 'portuguese' nativa: ela stemiza a palavra acentuada,
    # então "câmbio" indexado nunca casaria com "cambio" digitado. E o usuário
    # brasileiro digita sem acento na barra de busca. Com a config nativa, a
    # busca perderia resultados em silêncio — sem erro, só sem retorno.
    #
    # O mapping cobre `asciiword` E `word`. Cobrir só `word` (o erro fácil aqui)
    # deixaria de fora justamente o termo SEM acento — que é o caso do usuário.
    #
    # LIMITAÇÃO CONHECIDA: remover o acento antes de stemizar faz o snowball
    # perder a regra de plural -ões/-ão. Então "revisao" não acha "revisões".
    # É um trade-off inerente: a config nativa acerta o plural e erra o acento;
    # esta acerta o acento e erra esse plural. Escolhemos o acento porque é o
    # que o usuário realmente faz, e porque marca e modelo — o grosso das buscas
    # ("corolla", "civic", "onix") — são ASCII e não sofrem com nenhum dos dois.
    # Evolução natural, se virar dor real: índice pg_trgm como fallback fuzzy.
    # -------------------------------------------------------------------------
    op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS unaccent"))
    op.execute(sa.text("CREATE TEXT SEARCH CONFIGURATION portuguese_unaccent (COPY = portuguese)"))
    op.execute(
        sa.text(
            "ALTER TEXT SEARCH CONFIGURATION portuguese_unaccent "
            "ALTER MAPPING FOR asciiword, asciihword, hword_asciipart, "
            "word, hword, hword_part "
            "WITH unaccent, portuguese_stem"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=90), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_brands_slug"), "brands", ["slug"], unique=True)
    op.create_table(
        "dealerships",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("whatsapp", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dealerships_slug"), "dealerships", ["slug"], unique=True)
    op.create_table(
        "features",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=90), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "comfort",
                "safety",
                "technology",
                "performance",
                "exterior",
                "interior",
                name="feature_category",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_features_slug"), "features", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("dealership_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("super_admin", "admin", "seller", name="user_role"),
            server_default=sa.text("'seller'"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dealership_id"], ["dealerships.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_dealership_id"), "users", ["dealership_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "vehicle_models",
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=90), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand_id", "slug", name="uq_vehicle_models_brand_slug"),
    )
    op.create_index(
        op.f("ix_vehicle_models_brand_id"), "vehicle_models", ["brand_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["replaced_by_id"], ["refresh_tokens.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True
    )
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id", "revoked_at"], unique=False
    )
    op.create_table(
        "vehicles",
        sa.Column("dealership_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("brand_id", sa.UUID(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("brand_name", sa.String(length=80), nullable=False),
        sa.Column("model_name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=True),
        sa.Column("year_manufacture", sa.SmallInteger(), nullable=False),
        sa.Column("year_model", sa.SmallInteger(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("mileage", sa.Integer(), nullable=False),
        sa.Column(
            "fuel_type",
            sa.Enum(
                "flex",
                "gasoline",
                "ethanol",
                "diesel",
                "electric",
                "hybrid",
                "gnv",
                name="fuel_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "transmission",
            sa.Enum(
                "manual", "automatic", "cvt", "automated", "dual_clutch", name="transmission_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "body_type",
            sa.Enum(
                "hatch",
                "sedan",
                "suv",
                "pickup",
                "coupe",
                "convertible",
                "wagon",
                "minivan",
                "van",
                name="body_type",
            ),
            nullable=False,
        ),
        sa.Column("color", sa.String(length=40), nullable=False),
        sa.Column("doors", sa.SmallInteger(), nullable=True),
        sa.Column("engine", sa.String(length=40), nullable=True),
        sa.Column("horsepower", sa.SmallInteger(), nullable=True),
        sa.Column("owners_count", sa.SmallInteger(), nullable=True),
        sa.Column("has_manual", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("has_spare_key", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("ipva_paid", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("licensing_paid", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("service_history", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "accepts_financing", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("accepts_trade", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("down_payment", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("installments_count", sa.SmallInteger(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "reserved", "sold", "archived", name="vehicle_status"),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sold_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("views_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('portuguese_unaccent', coalesce(brand_name, '') || ' ' || coalesce(model_name, '') || ' ' || coalesce(version, '') || ' ' || coalesce(color, '') || ' ' || coalesce(city, '') || ' ' || coalesce(description, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mileage >= 0", name="ck_vehicles_mileage_non_negative"),
        sa.CheckConstraint("price > 0", name="ck_vehicles_price_positive"),
        sa.CheckConstraint("year_manufacture >= 1900", name="ck_vehicles_year_sane"),
        sa.CheckConstraint(
            "year_model >= year_manufacture", name="ck_vehicles_year_model_gte_manufacture"
        ),
        sa.ForeignKeyConstraint(["brand_id"], ["brands.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["dealership_id"], ["dealerships.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["model_id"], ["vehicle_models.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_vehicles_brand_model", "vehicles", ["brand_id", "model_id"], unique=False)
    op.create_index("ix_vehicles_city", "vehicles", ["city"], unique=False)
    op.create_index(op.f("ix_vehicles_dealership_id"), "vehicles", ["dealership_id"], unique=False)
    op.create_index(
        "ix_vehicles_dealership_status", "vehicles", ["dealership_id", "status"], unique=False
    )
    op.create_index(op.f("ix_vehicles_is_featured"), "vehicles", ["is_featured"], unique=False)
    op.create_index(
        "ix_vehicles_listing",
        "vehicles",
        ["status", "is_featured", "published_at"],
        unique=False,
        postgresql_using="btree",
    )
    op.create_index("ix_vehicles_price", "vehicles", ["price"], unique=False)
    op.create_index(
        "ix_vehicles_search", "vehicles", ["search_vector"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_vehicles_slug"), "vehicles", ["slug"], unique=True)
    op.create_index("ix_vehicles_year_model", "vehicles", ["year_model"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("dealership_id", sa.UUID(), nullable=False),
        sa.Column("customer_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("whatsapp", sa.String(length=20), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("scheduled_date", sa.Date(), nullable=False),
        sa.Column("scheduled_time", sa.Time(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "confirmed", "cancelled", "completed", name="appointment_status"),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["dealership_id"], ["dealerships.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_appointments_dealership_status",
        "appointments",
        ["dealership_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_appointments_status_date", "appointments", ["status", "scheduled_date"], unique=False
    )
    op.create_index(
        op.f("ix_appointments_vehicle_id"), "appointments", ["vehicle_id"], unique=False
    )
    op.create_table(
        "vehicle_features",
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("vehicle_id", "feature_id"),
    )
    op.create_index("ix_vehicle_features_feature", "vehicle_features", ["feature_id"], unique=False)
    op.create_table(
        "vehicle_images",
        sa.Column("vehicle_id", sa.UUID(), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("url", sa.String(length=700), nullable=False),
        sa.Column("alt_text", sa.String(length=200), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("position", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_cover", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["vehicle_id"], ["vehicles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_vehicle_images_vehicle_position",
        "vehicle_images",
        ["vehicle_id", "position"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vehicle_images_vehicle_position", table_name="vehicle_images")
    op.drop_table("vehicle_images")
    op.drop_index("ix_vehicle_features_feature", table_name="vehicle_features")
    op.drop_table("vehicle_features")
    op.drop_index(op.f("ix_appointments_vehicle_id"), table_name="appointments")
    op.drop_index("ix_appointments_status_date", table_name="appointments")
    op.drop_index("ix_appointments_dealership_status", table_name="appointments")
    op.drop_table("appointments")
    op.drop_index("ix_vehicles_year_model", table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_slug"), table_name="vehicles")
    op.drop_index("ix_vehicles_search", table_name="vehicles", postgresql_using="gin")
    op.drop_index("ix_vehicles_price", table_name="vehicles")
    op.drop_index("ix_vehicles_listing", table_name="vehicles", postgresql_using="btree")
    op.drop_index(op.f("ix_vehicles_is_featured"), table_name="vehicles")
    op.drop_index("ix_vehicles_dealership_status", table_name="vehicles")
    op.drop_index(op.f("ix_vehicles_dealership_id"), table_name="vehicles")
    op.drop_index("ix_vehicles_city", table_name="vehicles")
    op.drop_index("ix_vehicles_brand_model", table_name="vehicles")
    op.drop_table("vehicles")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_vehicle_models_brand_id"), table_name="vehicle_models")
    op.drop_table("vehicle_models")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_dealership_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_features_slug"), table_name="features")
    op.drop_table("features")
    op.drop_index(op.f("ix_dealerships_slug"), table_name="dealerships")
    op.drop_table("dealerships")
    op.drop_index(op.f("ix_brands_slug"), table_name="brands")
    op.drop_table("brands")
    # ### end Alembic commands ###

    # Os tipos ENUM não são removidos pelo autogenerate: ele os cria implicitamente
    # dentro do create_table, mas o drop_table não os desfaz. Sem estas linhas, um
    # `downgrade` deixa os tipos órfãos — e no dia em que os valores de um enum
    # mudarem, o `upgrade` seguinte reaproveitaria a definição antiga, em silêncio.
    # Um rollback tem que devolver o banco ao estado anterior de verdade.
    for enum_name in (
        "appointment_status",
        "vehicle_status",
        "body_type",
        "transmission_type",
        "fuel_type",
        "feature_category",
        "user_role",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS {enum_name}"))

    op.execute(sa.text("DROP TEXT SEARCH CONFIGURATION IF EXISTS portuguese_unaccent"))
    # A extensão `unaccent` NÃO é removida de propósito: é um objeto do banco
    # inteiro, e outro schema no mesmo Postgres pode depender dela. Derrubá-la
    # num rollback nosso quebraria vizinho inocente.
